extends:
  - prettier
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }]
  no-warning-comments: warn
